/**
 * Prove the container host backend, end to end, against a real container.
 *
 * The unit tests for `ContainerBackend` mock the runtime, so they can only show
 * that the right argv was assembled. This drives the whole path: a daemon on
 * its own port and home, `POST /v1/agents` with a `kind: "container"` spec, an
 * `omp acp` inside the container, a real model turn answered through the
 * daemon's own model broker, the approval gate answered over the client
 * websocket, and the grant refused once the agent is gone.
 *
 * What it no longer does, which is the point of this version.
 *
 * Until this rewrite the script copied the operator's `~/.omp/agent/agent.db`
 * into the mounted workspace so the guest could reach a model. The snapshot was
 * pruned to one provider and seven private tables were emptied, and none of
 * that made it safe: what crossed was still a real Anthropic OAuth credential,
 * sitting on a filesystem the guest could read, in a container that keeps full
 * unrestricted internet egress. Narrowing a reusable credential is not
 * confining it. Anything reusable that reaches a guest is off this machine the
 * moment the image is hostile, and the sandbox offers nothing to fall back on.
 * The docs now say ompd never hands a container a provider credential, and a
 * check script that did would be the repo violating its own claim.
 *
 * So the guest gets what a provisioned agent gets: a scoped bearer for exactly
 * one model on exactly one endpoint, the daemon's broker, which forwards to
 * `omp auth-gateway` on the host's loopback and resolves the operator's
 * credential there. The bearer is random, pinned to this container's network,
 * capped, and revoked on teardown. It is worth nothing anywhere else and
 * nothing at all afterwards, and the phases below assert both rather than
 * assuming them: the credential-shape scan is proved against a planted decoy
 * first, and the revocation probe refuses to read an unreachable broker as a
 * pass.
 *
 * The gate is the other part worth the trouble. `spawnLocalHost` writes the
 * overlay described in `docs/acp-approval-gate.md` to a path on the daemon's
 * machine, which does not exist inside the container; `gate-wrapper.ts` places
 * it in a directory the container has mounted read-only at `/run/ompd-gate`
 * and byte-verifies it on the daemon's own side, so the far side only ever
 * reads. Nothing about that had ever been watched against a real container.
 * An approval frame arriving at ompd at all is what proves the ACP permission
 * hook ran, since nothing else emits one; the failure text says which of the
 * two gates refused; and the overlay being unwritable from inside is what
 * stops the container serving itself a permissive one instead.
 *
 * One property was lost with the credential copy and is worth naming rather
 * than quietly dropping: the old snapshot carried the operator's `config.yml`
 * verbatim, `tools.approvalMode: yolo` and all, so a container that still asked
 * for approval proved the daemon's overlay outranked the guest's own config.
 * The guest's `config.yml` is now generated by the daemon and carries model
 * roles only, so that precedence is no longer exercised here. It belongs in a
 * unit test over the overlay, not in a script that has to be handed a
 * credential to express it.
 *
 * Everything it creates is removed, including on the failure path: the
 * container, the workspace, the daemon home, and the image unless
 * `--keep-image` is given.
 *
 * Usage:
 *   bun run scripts/check-container-host.ts [--keep-image] [--image <tag>]
 */

import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { assistantTextOf, GATE_CONFIG_YAML } from "../packages/acp/src/index.ts";
import type { Agent, AgentState } from "../packages/core/src/index.ts";
import { Ompd } from "../packages/daemon/src/index.ts";
import { GUEST_HOME_MOUNT } from "../packages/daemon/src/provisioner/guest-config.ts";

const SCRIPTS_DIR = dirname(fileURLToPath(import.meta.url));

/**
 * The operator's own omp config, read and never copied.
 *
 * The one thing taken from it is `modelRoles.default`, and only so this script
 * can say at preflight which model the container will be granted. It holds no
 * secret; the credential vault beside it is never opened, mounted or copied by
 * anything below.
 */
const HOST_OMP_CONFIG = join(homedir(), ".omp", "agent", "config.yml");

/** Where the omp release lands in the image. Must match `container-host.Dockerfile`. */
const IMAGE_OMP_PATH = "/usr/local/lib/omp/omp";

/** Where the Dockerfile installs the shim below, and the name `omp` resolves to on PATH. */
const IMAGE_SHIM_PATH = "/usr/local/bin/omp";

/**
 * `IMAGE_SHIM_PATH` inside the probe image.
 *
 * This used to be rendered from the daemon's own `renderOmpHomeShim`, whose
 * live purpose was picking up a credential-bearing OMP home seeded at
 * `$PWD/.omp-home`. That channel is gone. What remains is the one
 * non-credential job that shim also did, and the only reason a shim exists at
 * all: `container-host.Dockerfile` puts the release at `IMAGE_OMP_PATH` and
 * needs `omp` itself on PATH, because the container backend attaches with a
 * bare `omp` when the operator named the image (`image.ts`, `ompPath:
 * OMP_NAME`). Deliberately nothing else, so this image has no path by which a
 * seeded directory can become the guest's HOME behind the daemon's back.
 */
const PATH_SHIM = `#!/bin/sh
# Put the omp release on PATH under its own name, and nothing else. This script
# used to seed HOME from a directory in the workspace, which is how a provider
# credential reached the guest; the daemon now mounts a generated home holding
# one scoped bearer, and re-adding a seed here would defeat it.
set -eu
exec ${IMAGE_OMP_PATH} "$@"
`;

/** The guest's own view of the home the daemon seeded for it. */
const GUEST_TOKEN_PATH = `${GUEST_HOME_MOUNT}/.omp/model-token`;
const GUEST_MODELS_YML = `${GUEST_HOME_MOUNT}/.omp/agent/models.yml`;

/**
 * Value shapes a reusable provider credential has, as one `grep -E` pattern.
 *
 * Value prefixes only, never a schema word. `refresh_token` and `oauth` both
 * appear in the DDL of omp's own `auth_credentials` table, so a fresh guest
 * `agent.db` carries them with no credential anywhere near it, and a scan built
 * on them would report a finding on every clean run.
 *
 * Not vacuous, and not taken on faith either way. Measured against the very
 * snapshot this script used to hand over: the operator's `agent.db` carries
 * eight `sk-ant-` occurrences, four of them the `sk-ant-oat01-` access-token
 * prefix and four the `sk-ant-ort01-` refresh-token prefix. The scan below is
 * also run once against a planted decoy before it is trusted.
 */
const CREDENTIAL_SHAPES = "sk-ant-|sk-proj-|sk-or-v1-|github_pat_|ghp_|gho_|AIzaSy|xoxb-|xoxp-";

/** Markers live in the container's own /tmp, never in the mounted workspace. */
const DENY_MARKER = "/tmp/ompd-container-check-deny.txt";
const ALLOW_MARKER = "/tmp/ompd-container-check-allow.txt";

const TURN_TIMEOUT_MS = 300_000;
const APPROVAL_TIMEOUT_MS = 180_000;
/**
 * Shorter than a tool-using turn on purpose. The model turn asks for one token
 * of text and no tool, so a minute of silence is a failure rather than a slow
 * answer, and a run whose model access is broken should say so quickly instead
 * of sitting for five minutes per phase.
 */
const MODEL_TURN_TIMEOUT_MS = 120_000;

/** Regenerated per run, so a reply cannot be a cached or replayed one. */
const NONCE = `CONTAINERTURN-${randomBytes(5).toString("hex")}`;

interface Options {
  image: string;
  keepImage: boolean;
}

interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

interface ApprovalFrame {
  requestId: string;
  agentId: string;
  tool: string;
  title: string;
}

interface Check {
  name: string;
  ok: boolean;
  detail: string;
}

const checks: Check[] = [];
let step = 0;

function record(name: string, ok: boolean, detail = ""): boolean {
  checks.push({ name, ok, detail });
  console.log(`${ok ? "ok  " : "FAIL"} ${name}${detail ? `  ${detail}` : ""}`);
  return ok;
}

function phase(title: string): void {
  step += 1;
  console.log(`\n-- ${step}. ${title}`);
}

async function run(argv: string[]): Promise<RunResult> {
  const child = spawn(argv[0] ?? "", argv.slice(1), { stdio: ["ignore", "pipe", "pipe"] });
  let stdout = "";
  let stderr = "";
  child.stdout.on("data", (chunk: Buffer) => (stdout += chunk.toString()));
  child.stderr.on("data", (chunk: Buffer) => (stderr += chunk.toString()));
  const { promise, resolve } = Promise.withResolvers<RunResult>();
  child.on("error", err => resolve({ code: 127, stdout, stderr: String(err) }));
  child.on("close", code => resolve({ code: code ?? 0, stdout, stderr }));
  return await promise;
}

function parseOptions(argv: string[]): Options {
  let image = "ompd-container-host:probe";
  let keepImage = false;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--keep-image") {
      keepImage = true;
    } else if (arg === "--image") {
      const next = argv[i + 1];
      if (next === undefined) throw new Error("--image needs a tag");
      image = next;
      i += 1;
    } else {
      throw new Error(`unknown argument ${JSON.stringify(arg)}`);
    }
  }
  return { image, keepImage };
}

/**
 * A free loopback port for the daemon's model broker.
 *
 * Asked for rather than left at the default, because a hand-run check must not
 * fight the operator's own daemon over one fixed port. The daemon's broker
 * binds a container network's own gateway address, so two daemons on different
 * networks would not actually collide, but a check that fails on
 * `EADDRINUSE` for a reason unrelated to what it is testing is a check nobody
 * trusts.
 */
async function freePort(): Promise<number> {
  const probe = Bun.serve({ port: 0, hostname: "127.0.0.1", fetch: () => new Response("") });
  // Typed optional because a Bun server can be bound to a unix socket instead.
  // This one asked for a TCP port, so an absent one means the bind did not do
  // what it was told and nothing below would be testing the right listener.
  const port = probe.port;
  await probe.stop(true);
  if (port === undefined) throw new Error("Bun.serve bound no TCP port, so no broker port could be reserved");
  return port;
}

/**
 * The model the daemon will grant this container, or the reason it cannot.
 *
 * `containerModel` is left empty on purpose so this run uses the operator's own
 * `modelRoles.default`, which is the same resolution order a real container
 * provision follows. The daemon resolves it again for itself and refuses to
 * provision when nothing resolves, so this is not the authority; it exists so a
 * missing default is named here, at preflight, rather than arriving later as a
 * provisioning error whose cause has to be inferred. There is no fallback and
 * no invented default: an unresolvable model ends the run.
 */
function resolveContainerModel(configured: string): { model: string; from: string } | { error: string } {
  if (configured !== "") return { model: configured, from: "containerModel" };
  if (!existsSync(HOST_OMP_CONFIG)) {
    return {
      error:
        `containerModel is empty and ${HOST_OMP_CONFIG} does not exist, so there is no modelRoles.default to ` +
        `fall back to; select a default model in omp or set containerModel`,
    };
  }
  let parsed: unknown;
  try {
    parsed = Bun.YAML.parse(readFileSync(HOST_OMP_CONFIG, "utf8"));
  } catch (err) {
    return { error: `${HOST_OMP_CONFIG} does not parse as YAML, so modelRoles.default cannot be read: ${String(err)}` };
  }
  // Two guarded reads rather than a helper: `Reflect.get` throws on a
  // primitive, and a config whose `modelRoles` is a string rather than a map is
  // exactly the shape that would make it.
  const roles = parsed !== null && typeof parsed === "object" ? Reflect.get(parsed, "modelRoles") : undefined;
  const fallback = roles !== null && typeof roles === "object" ? Reflect.get(roles, "default") : undefined;
  if (typeof fallback !== "string" || fallback.trim() === "") {
    return {
      error:
        `containerModel is empty and ${HOST_OMP_CONFIG} names no modelRoles.default, so no model resolves; ` +
        `set one of the two rather than expecting a default`,
    };
  }
  return { model: fallback.trim(), from: `${HOST_OMP_CONFIG} modelRoles.default` };
}

/**
 * Build the probe image if it is not already present, and report whether this
 * run is the one that created it, because only that run may remove it.
 *
 * The omp release is downloaded into a throwaway build context rather than kept
 * in the repo: it is 150MB, and which build is correct depends on the
 * container's architecture rather than the checkout's.
 */
async function ensureImage(image: string): Promise<boolean> {
  if ((await run(["docker", "image", "inspect", image])).code === 0) {
    console.log(`  image ${image} already present, leaving it alone`);
    return false;
  }

  const arch = (await run(["docker", "info", "--format", "{{.Architecture}}"])).stdout.trim();
  const target = arch === "aarch64" || arch === "arm64" ? "arm64" : "x64";
  const version = (await run(["omp", "--version"])).stdout.trim().replace(/^omp\//, "");
  if (version === "") throw new Error("omp --version returned nothing; is omp on PATH?");

  const context = mkdtempSync(join(tmpdir(), "ompd-container-build-"));
  try {
    const url = `https://github.com/can1357/oh-my-pi/releases/download/v${version}/omp-linux-${target}`;
    console.log(`  downloading ${url}`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`downloading omp-linux-${target} failed: ${res.status}`);
    writeFileSync(join(context, "omp"), Buffer.from(await res.arrayBuffer()), { mode: 0o755 });
    cpSync(join(SCRIPTS_DIR, "container-host.Dockerfile"), join(context, "Dockerfile"));
    // The Dockerfile installs this as `/usr/local/bin/omp`, so the file has to
    // be here under the name it expects. See `PATH_SHIM` for why it is four
    // lines rather than the daemon's shim.
    writeFileSync(join(context, "omp-home-shim.sh"), PATH_SHIM, { mode: 0o755 });

    console.log(`  building ${image} for linux/${target}`);
    const built = await run(["docker", "build", "-t", image, context]);
    if (built.code !== 0) throw new Error(`docker build failed: ${built.stderr.slice(-800)}`);
    return true;
  } finally {
    rmSync(context, { recursive: true, force: true });
  }
}

async function api(base: string, token: string, path: string, init: RequestInit = {}): Promise<Response> {
  const headers = new Headers(init.headers);
  headers.set("authorization", `Bearer ${token}`);
  if (init.body !== undefined) headers.set("content-type", "application/json");
  return await fetch(`${base}${path}`, { ...init, headers });
}

/** A client websocket, authenticated and attached, with an approval queue. */
class Client {
  #ws: WebSocket;
  #approvals: ApprovalFrame[] = [];
  #waiters: Array<(a: ApprovalFrame | null) => void> = [];
  #errors: string[] = [];
  #failures: string[] = [];
  #assistant = "";
  #model = "";
  #hello = Promise.withResolvers<string>();

  constructor(ws: WebSocket) {
    this.#ws = ws;
    ws.addEventListener("message", event => {
      const frame = JSON.parse(String(event.data)) as Record<string, unknown>;
      if (frame.t === "hello") {
        this.#hello.resolve(String(frame.deviceId));
        return;
      }
      if (frame.t === "approval") {
        const approval: ApprovalFrame = {
          requestId: String(frame.requestId),
          agentId: String(frame.agentId),
          tool: String(frame.tool),
          title: String(frame.title),
        };
        const waiter = this.#waiters.shift();
        if (waiter) waiter(approval);
        else this.#approvals.push(approval);
        return;
      }
      if (frame.t === "update") {
        // The assistant's own words, which is the only thing that says a model
        // actually answered. `assistantTextOf` is the daemon's own reader, so a
        // change to the chunk shape cannot make this silently stop collecting.
        const text = assistantTextOf(frame.update);
        if (text !== null) {
          this.#assistant += text;
          return;
        }
        // `docs/acp-approval-gate.md`: a refusal from omp's own approval gate
        // reads "Tool call denied by user: bash", and one from the ACP
        // permission hook reads "Tool call rejected by user (bash)". Both stop
        // the tool, so the text is the only thing that says which gate ran.
        const update = frame.update as { sessionUpdate?: string; status?: string; model?: unknown } | null;
        if (update?.sessionUpdate === "tool_call_update" && update.status === "failed") {
          this.#failures.push(JSON.stringify(frame.update));
          return;
        }
        // Which model the guest's omp believes it is running. The guest has
        // exactly one, so this is checkable against the grant rather than
        // merely informative.
        if (update?.sessionUpdate === "session_info_update" && typeof update.model === "string") {
          this.#model = update.model;
        }
        return;
      }
      if (frame.t === "error") this.#errors.push(String(frame.message));
    });
  }

  /**
   * Resolves once the daemon has answered `hello`, which is the only proof the
   * token was accepted: an unauthenticated socket is closed rather than
   * refused, and a script that skipped this would read the silence that follows
   * as "no approval was ever requested".
   */
  static async open(base: string, token: string): Promise<Client> {
    const ws = new WebSocket(`${base.replace(/^http/, "ws")}/v1/socket?token=${token}`);
    const opened = Promise.withResolvers<void>();
    ws.addEventListener("open", () => opened.resolve());
    ws.addEventListener("error", () => opened.reject(new Error("websocket failed to open")));
    await opened.promise;
    const client = new Client(ws);
    await client.#hello.promise;
    return client;
  }

  get errors(): readonly string[] {
    return this.#errors;
  }

  /** Every `tool_call_update` that reported failure, as raw JSON. */
  get failures(): readonly string[] {
    return this.#failures;
  }

  /** Everything the assistant has said on this socket, concatenated. */
  get assistantText(): string {
    return this.#assistant;
  }

  /** The model the guest last reported, or empty if it never said. */
  get reportedModel(): string {
    return this.#model;
  }

  send(frame: Record<string, unknown>): void {
    this.#ws.send(JSON.stringify(frame));
  }

  /** Null on timeout, which is a finding to report rather than a crash. */
  async nextApproval(ms: number): Promise<ApprovalFrame | null> {
    const queued = this.#approvals.shift();
    if (queued) return queued;
    const { promise, resolve } = Promise.withResolvers<ApprovalFrame | null>();
    const timer = setTimeout(() => {
      this.#waiters = this.#waiters.filter(waiter => waiter !== resolve);
      resolve(null);
    }, ms);
    this.#waiters.push(approval => {
      clearTimeout(timer);
      resolve(approval);
    });
    return await promise;
  }

  close(): void {
    this.#ws.close();
  }
}

/**
 * Poll until the agent settles, and report which state it settled in.
 *
 * `failed` and `stopped` end the wait but are not success: a host that died
 * mid-turn also leaves no marker file behind, and reading that as a denial is
 * exactly the mistake `docs/acp-approval-gate.md` warns about.
 */
async function settle(base: string, token: string, agentId: string, ms: number): Promise<AgentState> {
  const deadline = Date.now() + ms;
  for (;;) {
    const body = (await (await api(base, token, "/v1/agents")).json()) as { agents: Agent[] };
    const agent = body.agents.find(candidate => candidate.id === agentId);
    const state = agent?.state;
    if (state === "idle" || state === "failed" || state === "stopped") return state;
    if (Date.now() > deadline) throw new Error(`agent ${agentId} never settled (state=${state})`);
    await Bun.sleep(1000);
  }
}

/**
 * Wait for a nonce to appear in the assistant's own reply.
 *
 * `settle` cannot serve here, and reaching for it is the obvious mistake: the
 * agent is `idle` before the prompt is picked up as well as after the turn
 * ends, so polling for `idle` returns immediately and reads a turn that never
 * happened as a turn that succeeded. The reply text is the only evidence a
 * model answered. A terminal state ends the wait early so a broken grant
 * reports in seconds rather than after the whole deadline.
 */
async function awaitNonce(
  base: string,
  token: string,
  agentId: string,
  client: Client,
  needle: string,
  ms: number,
): Promise<{ seen: boolean; state: AgentState | null }> {
  const deadline = Date.now() + ms;
  for (;;) {
    if (client.assistantText.includes(needle)) return { seen: true, state: null };
    const body = (await (await api(base, token, "/v1/agents")).json()) as { agents: Agent[] };
    const state = body.agents.find(candidate => candidate.id === agentId)?.state ?? null;
    if (state === "failed" || state === "stopped") return { seen: false, state };
    if (Date.now() > deadline) return { seen: false, state };
    await Bun.sleep(1000);
  }
}

/** A YAML double-quoted scalar the daemon wrote, read back out of the guest's config. */
function scalarFrom(yaml: string, key: string): string {
  const found = new RegExp(`^\\s*(?:- )?${key}: ("(?:[^"\\\\]|\\\\.)*")\\s*$`, "m").exec(yaml);
  if (found?.[1] === undefined) return "";
  const parsed: unknown = JSON.parse(found[1]);
  return typeof parsed === "string" ? parsed : "";
}

/**
 * Addresses a host process can try for a broker the guest reached.
 *
 * The guest's endpoint is taken from its own config rather than reconstructed,
 * so the probe goes to the address the container actually used. The second
 * candidate exists because the guest and the host do not share a name for the
 * same listener: under Docker Desktop a container reaches a host service bound
 * to loopback through `host.docker.internal`, which resolves to nothing on the
 * host itself. Both are tried and the first that answers HTTP is used.
 */
function brokerCandidates(endpoint: string): string[] {
  if (endpoint === "") return [];
  let url: URL;
  try {
    url = new URL(endpoint);
  } catch {
    return [];
  }
  const port = url.port === "" ? (url.protocol === "https:" ? "443" : "80") : url.port;
  const direct = `${url.protocol}//${url.host}`;
  const loopback = `${url.protocol}//127.0.0.1:${port}`;
  return direct === loopback ? [direct] : [direct, loopback];
}

/** The status of one broker request, or null when nothing answered at all. */
async function brokerStatus(url: string, path: string, init: RequestInit): Promise<number | null> {
  try {
    const res = await fetch(`${url}${path}`, { ...init, signal: AbortSignal.timeout(5000) });
    return res.status;
  } catch {
    return null;
  }
}

async function main(): Promise<number> {
  const opts = parseOptions(process.argv.slice(2));
  const home = mkdtempSync(join(tmpdir(), "ompd-container-home-"));
  const workspace = mkdtempSync(join(tmpdir(), "ompd-container-ws-"));
  let daemon: Ompd | undefined;
  let client: Client | undefined;
  let hostNetwork = "";
  let containerId = "";
  let builtImage = false;
  /**
   * The daemon's own log lines, kept as well as printed.
   *
   * The broker's request and token accounting is reported here and nowhere a
   * client can read: there is no API for "how much did this grant spend", and
   * inventing one to satisfy a check would be the check changing the product.
   * The revocation line is what proves the turn above actually went through the
   * broker rather than through anything else the guest might have found.
   */
  const daemonLog: string[] = [];
  /**
   * Everything this run puts outside its own temp directories, so the finally
   * block can take it all back. The canary is deliberately in the operator's
   * home, which is the whole point of it, and a probe that left it there would
   * be doing the thing it exists to prove is impossible.
   */
  const hostSideFiles: string[] = [
    join(homedir(), `.ompd-escape-canary-${process.pid}`),
    join(homedir(), "ompd-escape-test"),
  ];

  try {
    phase("preflight");
    const runtime = await run(["docker", "--version"]);
    if (!record("docker responds", runtime.code === 0, runtime.stdout.trim())) return 1;
    // Empty `containerModel`, so this resolves the operator's own default, the
    // same way a real provision does.
    const resolved = resolveContainerModel("");
    if (
      !record(
        "a model resolves for the container",
        !("error" in resolved),
        "error" in resolved ? resolved.error : `${resolved.model} from ${resolved.from}`,
      )
    ) {
      return 1;
    }
    builtImage = await ensureImage(opts.image);
    record("probe image available", true, opts.image);

    phase("start a daemon on its own port and home");
    const brokerPort = await freePort();
    daemon = new Ompd({
      home,
      overrides: {
        port: 0,
        host: "127.0.0.1",
        // Pinned rather than left to the platform default, which is Apple
        // `container` on darwin. Every confinement assertion below reads
        // docker's own `inspect` fields, and several of them describe flags
        // Apple's runtime rejects outright, so this script is docker's and says
        // so instead of provisioning somewhere it cannot check.
        containerRuntime: "docker",
        // The image is daemon config now rather than a wire field. `host.image`
        // is refused at the gateway on purpose: naming an image is
        // supply-chain approval by whoever owns the disk, and the image's
        // ENTRYPOINT runs before ompd has a process to gate, so no approval
        // could confine it. Set here it goes through `normalizeImageRef`, the
        // same check the wire would have applied.
        containerImage: opts.image,
        // The whole reason this script no longer copies a credential. On means
        // the daemon mints a per-container bearer for one model and seeds a
        // generated home for it; off would put the guest back to reaching
        // `idle` and failing every prompt.
        containerModelAccess: true,
        // Empty on purpose: resolve the operator's own `modelRoles.default`,
        // which `resolveContainerModel` reported above.
        containerModel: "",
        containerModelBrokerPort: brokerPort,
      },
      repoRoot: workspace,
      voice: false,
      onLog: line => {
        daemonLog.push(line);
        console.log(`  [daemon] ${line}`);
      },
    });
    const started = await daemon.start();
    const base = started.url;
    const token = readFileSync(join(home, "token"), "utf8").trim();
    record("daemon listening", true, `${base} home=${home}`);

    phase("provision a container host through POST /v1/agents");
    const before = await run(["docker", "ps", "-a", "--format", "{{.ID}}  {{.Image}}  {{.Status}}"]);
    console.log(`  docker ps -a before:\n${before.stdout.trimEnd() || "    (none)"}`);

    const created = await api(base, token, "/v1/agents", {
      method: "POST",
      body: JSON.stringify({
        name: "container-check",
        cwd: workspace,
        host: { kind: "container" },
      }),
    });
    const createdBody = (await created.json()) as { agent?: Agent; error?: string };
    if (!createdBody.agent) {
      // A refusal here is a finding, never a skip. Model access is on, so a
      // daemon that cannot grant it fails the provision by design rather than
      // producing an agent that reaches `idle` and answers nothing, and the
      // reason it gives names what is missing.
      record("agent created", false, `${created.status} ${createdBody.error ?? ""}`);
      return 1;
    }
    const agent = createdBody.agent;
    containerId = agent.host.id;
    record("agent created", created.status === 201, `${agent.id}`);
    record("host kind is container", agent.host.kind === "container", `${agent.host.kind}:${containerId.slice(0, 12)}`);
    record("agent reached idle", agent.state === "idle", `state=${agent.state}`);

    const running = await run(["docker", "inspect", "--format", "{{.State.Running}}", containerId]);
    record("container is running", running.stdout.trim() === "true", running.stdout.trim());

    phase("the gate overlay crossed into the container");
    // `container.ts` `GATE_MOUNT`. The overlay is delivered as a read-only
    // directory mount now rather than copied into a scratch directory the
    // container could write, which is the whole reason the path moved off
    // `/tmp`: a gate the far side can replace is not a gate. `GATE_MOUNT` is
    // module-private over there, so the path is written out here and named
    // rather than imported.
    const remote = "/run/ompd-gate/gate.yml";
    const overlay = await run(["docker", "exec", containerId, "cat", remote]);
    record("overlay is present on the far side", overlay.code === 0, remote);
    record("overlay is byte-identical", overlay.stdout === GATE_CONFIG_YAML, `${overlay.stdout.length} bytes`);
    // The property the mount delivery rests on. If the far side can write here
    // it can serve omp its own permissive overlay, and every gate assertion
    // below would then be measuring a gate the container chose.
    const overlayWrite = await run(["docker", "exec", containerId, "sh", "-c", `echo tampered > ${remote}`]);
    record(
      "the overlay cannot be rewritten from inside",
      overlayWrite.code !== 0,
      overlayWrite.stderr.trim().slice(0, 90),
    );

    phase("the container is not privileged");
    const cfg = await run([
      "docker",
      "inspect",
      "--format",
      "{{.HostConfig.Privileged}}|{{.HostConfig.ReadonlyRootfs}}|{{.HostConfig.CapDrop}}|{{.HostConfig.SecurityOpt}}|{{.Config.User}}|{{.HostConfig.PidsLimit}}",
      containerId,
    ]);
    const [privileged, readonlyRoot, capDrop, securityOpt, user, pids] = cfg.stdout.trim().split("|");
    record("not privileged", privileged === "false", `Privileged=${privileged}`);
    record("root filesystem is read-only", readonlyRoot === "true", `ReadonlyRootfs=${readonlyRoot}`);
    record("all capabilities dropped", capDrop === "[ALL]", `CapDrop=${capDrop}`);
    record("no-new-privileges is set", String(securityOpt).includes("no-new-privileges"), `SecurityOpt=${securityOpt}`);
    record("runs as a named non-root user", user !== "" && user !== "0:0", `User=${user}`);
    record("pids are bounded", Number(pids) > 0, `PidsLimit=${pids}`);

    const whoami = await run(["docker", "exec", containerId, "id", "-u"]);
    record("the process is not uid 0", whoami.stdout.trim() !== "0", `id -u = ${whoami.stdout.trim()}`);

    const nets = await run([
      "docker",
      "inspect",
      "--format",
      "{{range $name, $_ := .NetworkSettings.Networks}}{{$name}} {{end}}",
      containerId,
    ]);
    const joined = nets.stdout.trim();
    // Validated before it is ever used as a filter or an argument to rm: an
    // empty name matches every network, which would turn the teardown check
    // into a query about the whole machine.
    const named = /^ompd-[A-Za-z0-9]+$/.exec(joined.split(" ")[0] ?? "");
    hostNetwork = named?.[0] ?? "";
    record(
      "on exactly one network of its own, not the shared default bridge",
      hostNetwork !== "" && joined.split(/\s+/).filter(Boolean).length === 1,
      `networks=${joined || "(none)"}`,
    );

    phase("escape attempts");
    // Run through `docker exec`, which enters the container with exactly the
    // user and capability set the agent's bash tool inherits, since that tool
    // runs as a child of the `omp acp` this same mechanism started.
    const hostHome = homedir();

    const outsideWrite = await run([
      "docker",
      "exec",
      containerId,
      "sh",
      "-c",
      `echo escaped > ${hostHome}/ompd-escape-test`,
    ]);
    record(
      "cannot write outside the mounted workspace",
      outsideWrite.code !== 0 && !existsSync(join(hostHome, "ompd-escape-test")),
      outsideWrite.stderr.trim().slice(0, 90),
    );

    const rootWrite = await run(["docker", "exec", containerId, "sh", "-c", "echo escaped > /etc/ompd-escape"]);
    record("cannot write the image's own filesystem", rootWrite.code !== 0, rootWrite.stderr.trim().slice(0, 90));

    // A canary rather than only `~/.ssh`, because a machine without one would
    // make that test pass while proving nothing.
    const canary = hostSideFiles[0] ?? join(hostHome, ".ompd-escape-canary");
    writeFileSync(canary, "a secret the container must not reach\n", { mode: 0o600 });
    const readCanary = await run(["docker", "exec", containerId, "sh", "-c", `cat ${canary}`]);
    record("cannot read a file outside the workspace", readCanary.code !== 0, readCanary.stderr.trim().slice(0, 90));

    const sshDir = join(hostHome, ".ssh");
    if (existsSync(sshDir)) {
      const readSsh = await run(["docker", "exec", containerId, "sh", "-c", `ls -a ${sshDir}`]);
      record(
        "the host's ~/.ssh is not visible in the container",
        readSsh.code !== 0,
        readSsh.stderr.trim().slice(0, 90),
      );
    } else {
      console.log(`  (no ${sshDir} on this machine, so that attempt would prove nothing and is skipped)`);
    }

    // /dev/tcp is a bash builtin, so reaching for the daemon needs no network
    // tooling in the image. A container reaches its host by more than one name
    // and only the obvious one is isolated.
    const port = new URL(base).port;
    const loopback = await run([
      "docker",
      "exec",
      containerId,
      "bash",
      "-c",
      `timeout 5 bash -c 'exec 3<>/dev/tcp/127.0.0.1/${port}'`,
    ]);
    record(`ompd is not on the container's own loopback`, loopback.code !== 0, `exit ${loopback.code}`);

    // Measured, not asserted. Docker for Mac publishes the host under a name
    // that reaches services bound to 127.0.0.1, and a container that must also
    // reach a model endpoint cannot be cut off from the network without a
    // proxy in the path. So the question is not whether the daemon is
    // reachable but whether reaching it is worth anything, which is what the
    // two checks below settle.
    const viaHost = await run([
      "docker",
      "exec",
      containerId,
      "bash",
      "-c",
      `timeout 5 bash -c 'exec 3<>/dev/tcp/host.docker.internal/${port}'`,
    ]);
    if (viaHost.code !== 0) {
      record("the daemon's port is unreachable from the container", true, "no host route to it");
    } else {
      const unauth = await run([
        "docker",
        "exec",
        containerId,
        "bash",
        "-c",
        `timeout 5 bash -c 'exec 3<>/dev/tcp/host.docker.internal/${port}; printf "GET /v1/agents HTTP/1.1\\r\\nHost: ompd\\r\\nConnection: close\\r\\n\\r\\n" >&3; head -1 <&3'`,
      ]);
      record(
        "the daemon refuses the reachable container without a token",
        /401|403/.test(unauth.stdout),
        unauth.stdout.trim() || "(no status line)",
      );
    }

    const stealToken = await run(["docker", "exec", containerId, "sh", "-c", `cat ${join(home, "token")}`]);
    record("the daemon's token is not reachable from the container", stealToken.code !== 0, `exit ${stealToken.code}`);

    // The other half of the boundary: the workspace it was given must still
    // work, and what it writes there must belong to the operator rather than
    // to root.
    const inside = await run([
      "docker",
      "exec",
      containerId,
      "sh",
      "-c",
      `echo ok > ${workspace}/written-by-the-agent`,
    ]);
    record(
      "can still write its own workspace",
      inside.code === 0 && existsSync(join(workspace, "written-by-the-agent")),
      "",
    );
    const owner = statSync(join(workspace, "written-by-the-agent"), { throwIfNoEntry: false });
    record("workspace writes belong to the operator", owner?.uid === process.getuid?.(), `uid=${owner?.uid}`);

    phase("no reusable provider credential is reachable from inside");
    // The channel this script used to open. `.omp-home` in the workspace was
    // where the pruned `agent.db` snapshot went, and `/root/.omp` is the
    // image's own HOME, where a credential would land if the shim ever seeded
    // one again. Both are asserted absent from the guest's own view and from
    // the host's, because a mount can make one true and not the other.
    const legacySeed = await run(["docker", "exec", containerId, "sh", "-c", `ls -a "${workspace}/.omp-home"`]);
    record(
      "the workspace holds no seeded OMP home",
      legacySeed.code !== 0 && !existsSync(join(workspace, ".omp-home")),
      `exit ${legacySeed.code}`,
    );
    const imageVault = await run(["docker", "exec", containerId, "cat", "/root/.omp/agent/agent.db"]);
    record("the image's own HOME holds no credential vault", imageVault.code !== 0, `exit ${imageVault.code}`);

    // The guest's HOME must be the home the daemon seeded, and nothing in the
    // image may be able to move it. This is gated rather than commented
    // because the regression is silent and total: the shim this image used to
    // carry replaced HOME with a copy of `$PWD/.omp-home` whenever that
    // directory existed, which would discard the seeded models.yml and
    // config.yml and put the container straight back to "No model selected".
    const guestHomeEnv = await run(["docker", "exec", containerId, "printenv", "HOME"]);
    record(
      "the guest's HOME is the daemon-seeded mount",
      guestHomeEnv.stdout.trim() === GUEST_HOME_MOUNT,
      `HOME=${guestHomeEnv.stdout.trim() || "(unset)"} expected ${GUEST_HOME_MOUNT}`,
    );

    const imageShim = await run(["docker", "exec", containerId, "cat", IMAGE_SHIM_PATH]);
    record(
      "nothing on the image's omp path reassigns HOME",
      imageShim.code === 0 && !imageShim.stdout.includes(".omp-home") && !/\bHOME=/.test(imageShim.stdout),
      `${IMAGE_SHIM_PATH} is ${imageShim.stdout.split("\n").length} lines, exit ${imageShim.code}`,
    );

    // Observed rather than read off the script. Plant the directory the old
    // branch looked for, run omp through the image's own path with the
    // workspace as cwd, and look for what that branch would have left behind:
    // it copied the seed into a `mktemp -d /tmp/omp-home.XXXXXXXX` directory
    // before exec'ing. The probe prints a sentinel so an exec that failed
    // cannot read as an empty result.
    const plantedSeed = join(workspace, ".omp-home", ".omp", "agent");
    mkdirSync(plantedSeed, { recursive: true });
    const shimRan = await run(["docker", "exec", "--workdir", workspace, containerId, IMAGE_SHIM_PATH, "--version"]);
    const strays = await run([
      "docker",
      "exec",
      containerId,
      "sh",
      "-c",
      "ls -d /tmp/omp-home.* 2>/dev/null; echo PROBE-COMPLETE",
    ]);
    const strayLines = strays.stdout.trim().split("\n").filter(Boolean);
    record(
      "a workspace .omp-home cannot become the guest's HOME",
      strayLines.length === 1 && strayLines[0] === "PROBE-COMPLETE",
      `omp --version exit ${shimRan.code}, /tmp seeds: ${strayLines.filter(line => line !== "PROBE-COMPLETE").join(", ") || "(none)"}`,
    );
    rmSync(join(workspace, ".omp-home"), { recursive: true, force: true });

    // Read once, from the guest's own view. Held in memory only, never printed,
    // never written to disk, never placed in an argv: it is the live bearer for
    // this container's grant and the revocation phase needs it after teardown.
    const tokenRead = await run(["docker", "exec", containerId, "cat", GUEST_TOKEN_PATH]);
    const guestBearer = tokenRead.stdout.trim();
    record(
      "the guest holds a scoped model bearer of its own",
      tokenRead.code === 0 && guestBearer !== "",
      `${guestBearer.length} chars at ${GUEST_TOKEN_PATH}, not shown`,
    );

    const tokenStat = await run(["docker", "exec", containerId, "stat", "-c", "%a", GUEST_TOKEN_PATH]);
    record("the bearer file is 0600", tokenStat.stdout.trim() === "600", `mode=${tokenStat.stdout.trim() || "(none)"}`);

    const modelsRead = await run(["docker", "exec", containerId, "cat", GUEST_MODELS_YML]);
    const guestModelsYml = modelsRead.stdout;
    const grantedModel = scalarFrom(guestModelsYml, "id");
    const guestEndpoint = scalarFrom(guestModelsYml, "baseUrl");
    record(
      "models.yml reads the bearer with !cat rather than embedding it",
      modelsRead.code === 0 &&
        guestModelsYml.includes(`!cat ${GUEST_TOKEN_PATH}`) &&
        guestBearer !== "" &&
        !guestModelsYml.includes(guestBearer),
      `apiKey is a command, grant is ${grantedModel || "(unread)"} on ${guestEndpoint || "(unread)"}`,
    );
    record(
      "the guest was pointed at the broker port this run configured",
      guestEndpoint !== "" && new URL(guestEndpoint).port === String(brokerPort),
      `endpoint=${guestEndpoint || "(unread)"} configured=${brokerPort}`,
    );

    // Exactly one file in the seeded home may carry the bearer's own bytes, and
    // it is the 0600 token file. The pattern is passed through a command
    // substitution inside the container so the secret is in no argv on either
    // side. An unreadable token file turns this into `grep -F ""`, which
    // matches every file and fails loudly rather than quietly passing.
    const bearerCopies = await run([
      "docker",
      "exec",
      containerId,
      "sh",
      "-c",
      `grep -rlF "$(cat ${GUEST_TOKEN_PATH})" ${GUEST_HOME_MOUNT} 2>/dev/null | sort`,
    ]);
    const carriers = bearerCopies.stdout.trim().split("\n").filter(Boolean);
    record(
      "exactly one file in the seeded home carries the bearer",
      carriers.length === 1 && carriers[0] === GUEST_TOKEN_PATH,
      carriers.length === 0 ? "(nothing matched, so the token was unreadable)" : carriers.join(", "),
    );

    // A check that cannot fail is not a check. Prove the credential scan sees a
    // credential shape before trusting it to report none, then remove the decoy
    // and scan for real.
    //
    // One argv, run twice, because the decoy proves nothing unless the command
    // that finds it is byte for byte the command that later reports nothing.
    const scanRoots = `${GUEST_HOME_MOUNT} /root /home ${workspace}`;
    const scanArgv = [
      "docker",
      "exec",
      containerId,
      "sh",
      "-c",
      `grep -rlE '${CREDENTIAL_SHAPES}' ${scanRoots} 2>/dev/null | sort`,
    ];
    const decoy = join(workspace, "credential-shape-decoy.txt");
    writeFileSync(decoy, "sk-ant-oat01-DECOYDECOYDECOYDECOY\n", { mode: 0o600 });
    const decoyScan = await run(scanArgv);
    record(
      "the credential scan detects a planted credential shape",
      decoyScan.stdout.includes(decoy),
      decoyScan.stdout.trim().replace(/\n/g, ", ") || "(the scan found nothing, so it proves nothing)",
    );
    rmSync(decoy, { force: true });

    const realScan = await run(scanArgv);
    record(
      "no provider-credential value shape anywhere the guest can read",
      realScan.stdout.trim() === "",
      realScan.stdout.trim().replace(/\n/g, ", ") || `scanned ${scanRoots}`,
    );

    phase("a real model turn through the daemon's broker");
    client = await Client.open(base, token);
    client.send({ t: "attach", agentId: agent.id });
    client.send({
      t: "prompt",
      agentId: agent.id,
      text: `Reply with exactly this token and nothing else: ${NONCE}\nThat is the entire task. Do not use any tool.`,
    });
    const turn = await awaitNonce(base, token, agent.id, client, NONCE, MODEL_TURN_TIMEOUT_MS);
    if (
      !record(
        "the container completed a real model turn",
        turn.seen,
        turn.seen
          ? `reply carries ${NONCE}`
          : `no nonce in ${client.assistantText.length} chars of reply; state=${turn.state ?? "unknown"} ` +
              `errors=${client.errors.join(" | ") || "(none)"}`,
      )
    ) {
      console.log("\n  A container that cannot answer a prompt cannot decide to call a tool, so");
      console.log("  every gate phase below would pass against a host that never ran. Stopping.");
      return 1;
    }
    const afterTurn = await settle(base, token, agent.id, TURN_TIMEOUT_MS);
    record("the agent settled after the turn", afterTurn === "idle", `state=${afterTurn}`);
    // Not `session_info_update`: omp never emits one on this path, so a check
    // reading it can only ever fail. What is observable is the broker's own
    // accounting, which it reports when the grant is revoked in the destroy
    // phase below. A grant that served zero requests would mean the reply above
    // came from somewhere other than the broker, which given the credential
    // scan should be impossible -- so it is asserted rather than assumed.
    console.log(`  the guest reported its model as: ${client.reportedModel || "(it never said)"}`);

    phase("deny a bash call");
    client.send({
      t: "prompt",
      agentId: agent.id,
      text: `Use your bash tool to run exactly: touch ${DENY_MARKER}\nThat is the entire task. Do not use any other tool, and do not retry if it is refused.`,
    });

    const denyAsk = await client.nextApproval(APPROVAL_TIMEOUT_MS);
    if (
      !record(
        "permission request reached ompd",
        denyAsk !== null,
        denyAsk ? `tool=${denyAsk.tool} title=${denyAsk.title.slice(0, 60)}` : "no approval frame arrived",
      )
    ) {
      console.log("\n  The gate did not survive the trip. Everything below would also pass");
      console.log("  against an ungated host, so the run stops here.");
      return 1;
    }
    client.send({ t: "decide", agentId: agent.id, requestId: denyAsk?.requestId, choice: "deny", scope: "once" });

    const afterDeny = await settle(base, token, agent.id, TURN_TIMEOUT_MS);
    record("agent survived the denial", afterDeny === "idle", `state=${afterDeny}`);
    const denyText = client.failures.join(" ");
    console.log(`  tool failure text: ${denyText.slice(0, 240) || "(none reported)"}`);
    record(
      "denial came from the ACP hook, not omp's own gate",
      !/denied by user/.test(denyText),
      /rejected by user/.test(denyText) ? "saw 'rejected by user', which is gate 1" : "no gate-2 wording present",
    );
    const denied = await run(["docker", "exec", containerId, "test", "-f", DENY_MARKER]);
    record("denied command did not run", denied.code !== 0, `${DENY_MARKER} exists=${denied.code === 0}`);

    phase("allow a bash call");
    client.send({
      t: "prompt",
      agentId: agent.id,
      text: `Use your bash tool to run exactly: uname -s > ${ALLOW_MARKER}\nThat is the entire task. Do not use any other tool.`,
    });
    const allowAsk = await client.nextApproval(APPROVAL_TIMEOUT_MS);
    if (!record("second permission request reached ompd", allowAsk !== null, allowAsk?.tool ?? "none")) return 1;
    client.send({ t: "decide", agentId: agent.id, requestId: allowAsk?.requestId, choice: "allow", scope: "once" });

    const afterAllow = await settle(base, token, agent.id, TURN_TIMEOUT_MS);
    record("agent settled after the allow", afterAllow === "idle", `state=${afterAllow}`);
    const body = await run(["docker", "exec", containerId, "cat", ALLOW_MARKER]);
    record("allowed command ran", body.code === 0, `${ALLOW_MARKER} readable=${body.code === 0}`);
    record(
      "it ran inside the container",
      body.stdout.trim() === "Linux",
      `uname -s = ${body.stdout.trim() || "(empty)"}`,
    );

    phase("audit");
    const auditRes = await api(base, token, "/v1/audit?limit=200");
    // Kept as text as well as parsed, because one of the two things asked of
    // the audit log is that a value never appears in it, and that question is
    // about the bytes rather than about any field this script knows to read.
    const auditText = await auditRes.text();
    const audit = JSON.parse(auditText) as { entries: Array<{ action: string; outcome: string }> };
    const decisions = audit.entries.filter(entry => entry.action === "approval.decide");
    record(
      "both decisions are in the audit log",
      decisions.some(d => d.outcome === "denied") && decisions.some(d => d.outcome === "ok"),
      decisions.map(d => d.outcome).join(",") || "(none)",
    );
    record(
      "the grant is audited",
      audit.entries.some(entry => entry.action === "model.grant"),
      audit.entries
        .filter(entry => entry.action.startsWith("model."))
        .map(entry => `${entry.action}:${entry.outcome}`)
        .join(",") || "(no model.* rows)",
    );
    record(
      "no audit row carries the guest's bearer",
      guestBearer !== "" && !auditText.includes(guestBearer),
      `${auditText.length} bytes scanned`,
    );
    record("no socket errors", client.errors.length === 0, client.errors.join(" | "));

    phase("destroy");
    const stopped = await api(base, token, `/v1/agents/${agent.id}`, { method: "DELETE" });
    record("agent stopped", stopped.status === 200, String(stopped.status));

    // The broker reports what the grant spent as it revokes it. Non-zero
    // requests is the proof the model turn went through the broker, and the
    // model it names is the proof it was the granted one.
    const spent = /model broker: revoked a grant for (\S+) \((\d+) requests?, (\d+) tokens? used\)/.exec(
      daemonLog.join("\n"),
    );
    record(
      "the broker served the turn on the granted model",
      spent !== null && spent[1] === grantedModel && grantedModel !== "" && Number(spent[2]) > 0,
      spent === null
        ? "the broker never reported revoking a grant"
        : `${spent[1]}: ${spent[2]} requests, ${spent[3]} tokens (granted ${grantedModel || "(unread)"})`,
    );

    const after = await run(["docker", "ps", "-a", "--format", "{{.ID}}  {{.Image}}  {{.Status}}"]);
    console.log(`  docker ps -a after:\n${after.stdout.trimEnd() || "    (none)"}`);
    record("container removed", !after.stdout.includes(containerId.slice(0, 12)), containerId.slice(0, 12));

    if (hostNetwork === "") {
      record("its network was removed with it", false, "never captured a valid network name");
    } else {
      const netsLeft = await run([
        "docker",
        "network",
        "ls",
        "--format",
        "{{.Name}}",
        "--filter",
        `name=${hostNetwork}`,
      ]);
      record("its network was removed with it", netsLeft.stdout.trim() === "", hostNetwork);
    }

    phase("the bearer the guest held is refused now");
    // The trap this phase exists to avoid: after teardown the container and its
    // network are gone, so a request that cannot connect proves nothing about
    // the grant. A broker that closed refuses everything for the wrong reason,
    // and reading that as revocation would be a check that passes hardest when
    // it is broken. So liveness is established first, and only then is the
    // bearer presented.
    //
    // Any non-allowlisted request is the liveness signal: the broker's routable
    // surface is exactly `POST /v1/messages` and `POST /v1/messages/count_tokens`,
    // and everything else gets a real 404 before any credential is looked at. It
    // needs no bearer and has no side effect.
    const candidates = brokerCandidates(guestEndpoint);
    let live = "";
    let liveStatus: number | null = null;
    for (const candidate of candidates) {
      const status = await brokerStatus(candidate, "/v1/healthz", { method: "GET" });
      if (status !== null) {
        live = candidate;
        liveStatus = status;
        break;
      }
    }
    if (
      record(
        "the broker is still listening, so a refusal below means revoked and not gone",
        live !== "" && liveStatus === 404,
        live === ""
          ? `nothing answered at ${candidates.join(" or ") || "(no endpoint captured)"}, so revocation is UNPROVEN`
          : `${live} -> ${liveStatus}`,
      )
    ) {
      const refused = await brokerStatus(live, "/v1/messages", {
        method: "POST",
        headers: { authorization: `Bearer ${guestBearer}`, "content-type": "application/json" },
        body: JSON.stringify({
          model: grantedModel,
          max_tokens: 16,
          messages: [{ role: "user", content: `revoked? ${NONCE}` }],
        }),
      });
      record(
        "the bearer is refused now the agent is gone",
        refused === 401,
        `POST /v1/messages -> ${refused === null ? "no answer" : refused}`,
      );
    }
  } finally {
    // Each step is guarded on its own: one failing cleanup must not skip the
    // rest, and a probe that leaks a container is worse than a probe that
    // fails.
    try {
      client?.close();
    } catch (err) {
      console.log(`  cleanup: closing the socket failed: ${String(err)}`);
    }
    try {
      await daemon?.stop();
    } catch (err) {
      console.log(`  cleanup: stopping the daemon failed: ${String(err)}`);
    }
    if (containerId) {
      const still = await run(["docker", "ps", "-aq", "--filter", `id=${containerId}`]);
      if (still.stdout.trim() !== "") {
        const forced = await run(["docker", "rm", "--force", containerId]);
        console.log(`  cleanup: force-removed a surviving container (exit ${forced.code})`);
      }
    }
    if (hostNetwork) {
      const left = await run(["docker", "network", "ls", "-q", "--filter", `name=${hostNetwork}`]);
      if (left.stdout.trim() !== "") {
        const forced = await run(["docker", "network", "rm", hostNetwork]);
        console.log(`  cleanup: removed a surviving network ${hostNetwork} (exit ${forced.code})`);
      }
    }
    for (const dir of [workspace, home]) {
      try {
        rmSync(dir, { recursive: true, force: true });
      } catch (err) {
        console.log(`  cleanup: removing ${dir} failed: ${String(err)}`);
      }
    }
    for (const path of hostSideFiles) {
      if (!existsSync(path)) continue;
      try {
        rmSync(path, { force: true });
        console.log(`  cleanup: removed ${path}`);
      } catch (err) {
        console.log(`  cleanup: removing ${path} failed, remove it by hand: ${String(err)}`);
      }
    }
    if (builtImage && !opts.keepImage) {
      const removed = await run(["docker", "rmi", "--force", opts.image]);
      console.log(`  cleanup: removed image ${opts.image} (exit ${removed.code})`);
    }
    console.log("  cleanup: workspace and daemon home removed");
  }

  const failed = checks.filter(check => !check.ok);
  console.log(`\n${checks.length - failed.length} ok, ${failed.length} failed`);
  return failed.length === 0 ? 0 : 1;
}

process.exit(await main());
