/**
 * Generate the module that embeds the built web console into the CLI binary.
 *
 * `defaultStaticRoot()` looks for `packages/web/dist` relative to the source
 * tree. That works from a checkout and is exactly wrong for the installed
 * artifact: a compiled binary has no source tree, so the console silently
 * became API-only and `ompd open` opened a page answering
 * `{"error":"not_found"}`.
 *
 * Assets are inlined as base64 rather than imported with `{ type: "file" }`.
 * Bun embeds either way, but the import form has no usable TypeScript types
 * for `.webmanifest`, `.png`, or `.svg`, and `.html` resolves to an HTMLBundle
 * rather than a path. Base64 is larger on disk and simpler in every other way:
 * one string per asset, no module resolution, no ambient declarations.
 *
 * Run by `bun run build:cli`, after the web build and before the compile.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const dist = join(repoRoot, "packages", "web", "dist");
const out = join(repoRoot, "packages", "daemon", "src", "web-assets.ts");

function walk(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else found.push(full);
  }
  return found;
}

if (!existsSync(join(dist, "index.html"))) {
  // Fail rather than emit an API-only binary. Shipping an artifact whose
  // console silently 404s is the exact defect this file exists to fix, and a
  // release build must not be able to produce one by omission.
  console.error("packages/web/dist/index.html is missing, refusing to generate an empty console.");
  console.error("Run: bun run --cwd packages/web build");
  process.exit(1);
}

const files = walk(dist)
  // Source maps are large and only useful alongside sources that are not shipped.
  .filter(file => !file.endsWith(".map"))
  .sort();

const entries = files.map(file => {
  const urlPath = `/${relative(dist, file).split("\\").join("/")}`;
  const base64 = readFileSync(file).toString("base64");
  return `  ${JSON.stringify(urlPath)}: ${JSON.stringify(base64)},`;
});

const bytes = files.reduce((sum, file) => sum + statSync(file).size, 0);

writeFileSync(
  out,
  `// GENERATED by scripts/gen-web-assets.ts. Do not edit.
//
// Embeds the built web console so the compiled binary serves it. Without this
// the installed artifact answers {"error":"not_found"} at / because it has no
// source tree in which to find packages/web/dist.
//
// ${files.length} files, ${bytes} bytes before base64.

/** URL path to base64 file contents. */
export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};

export const WEB_ASSETS_BUILT = true;
`,
);

console.log(`embedded ${files.length} web asset(s), ${bytes} bytes, into packages/daemon/src/web-assets.ts`);
