/**
 * Generate the module that embeds the built web console into the CLI binary.
 *
 * `defaultStaticRoot()` looks for `packages/app/dist` relative to the source
 * tree. That works from a checkout and is exactly wrong for the installed
 * artifact: a compiled binary has no source tree, so the console silently
 * became API-only and `ompd open` opened a page answering
 * `{"error":"not_found"}`.
 *
 * Assets are inlined as base64 rather than imported with `{ type: "file" }`.
 * Bun embeds either way, but the import form has no usable TypeScript types
 * for `.webmanifest`, `.png`, or `.svg`, and `.html` resolves to an HTMLBundle
 * rather than a path. Base64 is larger on disk and simpler in every other way:
 * one string per asset, no module resolution, no ambient declarations.
 *
 * Run by `bun scripts/build-cli.ts` during release binary compilation.
 * With `--stub`, writes the tiny tracked stub so git never stores the multi-MB blob.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const defaultDist = join(repoRoot, "packages", "app", "dist");
const defaultOut = join(repoRoot, "packages", "daemon", "src", "web-assets.ts");

function walk(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else found.push(full);
  }
  return found;
}

export function generateWebAssets(opts: { distDir?: string; outFile?: string; stub?: boolean } = {}): void {
  const dist = opts.distDir ?? defaultDist;
  const out = opts.outFile ?? defaultOut;

  if (opts.stub) {
    writeFileSync(
      out,
      `// GENERATED by scripts/gen-web-assets.ts. Do not edit.
//
// Tracked stub form. The compiled CLI binary regenerates this module with the
// real built web console during scripts/build-cli.ts and restores this stub
// afterwards, so git history never stores multi-megabyte base64 blobs.
//
// In dev and source checkouts, the daemon serves from defaultStaticRoot()
// (packages/app/dist) when available.

/** URL path to base64 file contents. */
export const WEB_ASSETS: Record<string, string> = {};

export const WEB_ASSETS_BUILT = false;
`,
    );
    console.log(`wrote web assets stub into ${out}`);
    return;
  }

  if (!existsSync(join(dist, "index.html"))) {
    console.error(`${dist}/index.html is missing, refusing to generate an empty console.`);
    console.error("Run: bun run --cwd packages/app build:web");
    process.exit(1);
  }

  const files = walk(dist)
    .filter(file => !file.endsWith(".map"))
    .sort();

  const entries = files.map(file => {
    const urlPath = `/${relative(dist, file).split("\\").join("/")}`;
    const base64 = readFileSync(file).toString("base64");
    return `  ${JSON.stringify(urlPath)}: ${JSON.stringify(base64)},`;
  });

  const bytes = files.reduce((sum, file) => sum + statSync(file).size, 0);

  writeFileSync(
    out,
    `// GENERATED by scripts/gen-web-assets.ts. Do not edit.
//
// Embeds the built web console so the compiled binary serves it. Without this
// the installed artifact answers {"error":"not_found"} at / because it has no
// source tree in which to find packages/app/dist.
//
// ${files.length} files, ${bytes} bytes before base64.

/** URL path to base64 file contents. */
export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};

export const WEB_ASSETS_BUILT = true;
`,
  );

  console.log(`embedded ${files.length} web asset(s), ${bytes} bytes, into ${out}`);
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const stub = args.includes("--stub");
  const distIdx = args.indexOf("--dist");
  const distArg = distIdx >= 0 ? args[distIdx + 1] : undefined;
  const distDir = distArg !== undefined ? resolve(distArg) : undefined;
  const outIdx = args.indexOf("--out");
  const outArg = outIdx >= 0 ? args[outIdx + 1] : undefined;
  const outFile = outArg !== undefined ? resolve(outArg) : undefined;

  generateWebAssets({ stub, distDir, outFile });
}
