#!/usr/bin/env bun
/**
 * Generate the module that embeds the omp bridge extension into the CLI.
 *
 * `ompd install` writes the extension into omp's extensions directory, and it
 * has to be able to do that from an installed binary, which has no source tree
 * to copy from. Compiled artifacts only carry what the bundle imported, so the
 * extension source has to reach the bundle as a value.
 *
 * Embedded as one string rather than imported with `{ type: "text" }` for the
 * same reason `gen-web-assets.ts` inlines base64 instead of `{ type: "file" }`:
 * Bun would embed either way, but the import form has no usable TypeScript
 * types for a `.ts` file read as text, and an ambient declaration for that is
 * more machinery than one generated constant.
 *
 * `packages/cli/test/ompd-extension.test.ts` fails when the generated copy and
 * the source diverge, so a stale artifact cannot ship quietly.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const source = join(repoRoot, "packages", "omp-extension", "src", "index.ts");
const out = join(repoRoot, "packages", "cli", "src", "omp-bridge-source.ts");

const contents = readFileSync(source, "utf8");
if (!contents.includes("export default function ompdBridge")) {
  // The extension loader selects `module.default` and rejects anything that is
  // not a function. Generating a file without that export would install an
  // extension omp refuses to load, and the refusal would surface as a load
  // error in someone's session rather than here.
  console.error(`${source} has no default extension factory; refusing to generate an unloadable extension.`);
  process.exit(1);
}

writeFileSync(
  out,
  `// GENERATED by scripts/gen-omp-bridge.ts. Do not edit.
//
// The omp bridge extension, verbatim, so \`ompd install\` can write it into
// omp's extensions directory from a compiled binary that has no source tree.
//
// Base64 for the same reason \`gen-web-assets.ts\` uses it: the source is full
// of quotes, backticks and interpolation sequences, and a generated literal
// carrying those is a formatter argument and a lint suppression waiting to
// happen.
//
// ${contents.split("\n").length} lines, ${Buffer.byteLength(contents, "utf8")} bytes before base64.

const ENCODED =
  "${Buffer.from(contents, "utf8").toString("base64")}";

/** \`packages/omp-extension/src/index.ts\`, byte for byte. */
export const OMP_BRIDGE_SOURCE = Buffer.from(ENCODED, "base64").toString("utf8");
`,
);
console.log(`embedded ${Buffer.byteLength(contents, "utf8")} bytes of extension source into ${out}`);
