// GENERATED by scripts/gen-web-assets.ts. Do not edit.
//
// Tracked stub form. The compiled CLI binary regenerates this module with the
// real built web console during scripts/build-cli.ts and restores this stub
// afterwards, so git history never stores multi-megabyte base64 blobs.
//
// In dev and source checkouts, the daemon serves from defaultStaticRoot()
// (packages/app/dist) when available.

/** URL path to base64 file contents. */
export const WEB_ASSETS: Record<string, string> = {};

export const WEB_ASSETS_BUILT = false;
