/**
 * How a remote host keeps the approval gate.
 *
 * `spawnLocalHost` owns the gate: it writes the overlay described in
 * `docs/acp-approval-gate.md` and passes `--config <path>` itself. ompd is
 * forbidden from passing `--config`, and `spawnLocalHost` rejects any attempt,
 * because an overlay loaded after ours could set `approvalMode: yolo` and
 * remove the gate silently.
 *
 * That leaves one problem for container and cloud hosts: the overlay path
 * exists on the daemon's filesystem, and the `omp acp` process does not run
 * there. Rather than weaken the gate, the remote backends point
 * `spawnLocalHost` at a generated wrapper script. `spawnLocalHost` still writes
 * its own overlay and still passes its own `--config`; the wrapper copies that
 * exact file to the far side, verifies it byte for byte, rewrites the flag to
 * the far-side path, and execs. Nothing about the gate is reinterpreted, and
 * every failure exits non-zero rather than starting an ungated host.
 *
 * One constraint shapes the generated script: far-side commands must be plain
 * argv with no shell metacharacters, because ssh joins its arguments into a
 * single string for the remote shell to parse, so quoting that survives
 * `docker exec` does not survive ssh. Redirects in the script below are local
 * to the wrapper, never sent to the far side.
 */

import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ProvisionError } from "./types.ts";

export interface GateWrapperSpec {
  /**
   * Argv prefix that runs a plain command on the far side with stdin attached,
   * e.g. `["docker", "exec", "-i", "<id>"]` or `["ssh", "-T", "host"]`.
   */
  shell: string[];
  /**
   * Argv prefix that execs the far-side omp binary, e.g.
   * `["docker", "exec", "-i", "<id>", "omp"]`. Must end with the binary: the
   * wrapper appends the rewritten `acp --config ...` arguments to it.
   */
  attach: string[];
  /** Absolute path the overlay is copied to on the far side. */
  remoteConfigPath: string;
  /** Appears in the script's error messages. */
  label: string;
  /** Host kind, for `ProvisionError`. */
  kind: string;
}

export interface GateWrapper {
  /** Pass as `ompPath` to `spawnLocalHost`. */
  path: string;
  /** Private directory holding the script. Remove this, not just the file. */
  dir: string;
}

/**
 * Characters that survive both a local `sh` word and ssh's argv-to-string
 * round trip untouched. Anything else is refused rather than escaped: a
 * container id or ssh destination containing a quote is a sign something is
 * wrong upstream, and escaping it would hide that.
 */
const SAFE_TOKEN = /^[A-Za-z0-9_@%+=:,./-]+$/;

function renderArgv(argv: string[], what: string, kind: string): string {
  if (argv.length === 0) throw new ProvisionError(`${what} is empty`, kind);
  const unsafe = argv.find((token) => !SAFE_TOKEN.test(token));
  if (unsafe !== undefined) {
    throw new ProvisionError(`${what} contains an unsafe token ${JSON.stringify(unsafe)}`, kind);
  }
  return argv.join(" ");
}

/**
 * Render the wrapper script. Exported for tests, which assert on its fail-closed
 * behaviour by running it against a fake runtime.
 */
export function renderGateWrapper(spec: GateWrapperSpec): string {
  const shell = renderArgv(spec.shell, "far-side shell command", spec.kind);
  const attach = renderArgv(spec.attach, "far-side attach command", spec.kind);
  if (!SAFE_TOKEN.test(spec.remoteConfigPath)) {
    throw new ProvisionError(
      `far-side overlay path ${JSON.stringify(spec.remoteConfigPath)} is not a safe token`,
      spec.kind,
    );
  }
  const label = spec.label.replace(/[^A-Za-z0-9 _.:@/-]/g, ".");
  const remote = spec.remoteConfigPath;

  return `#!/bin/sh
# Generated by ompd for ${label}. Do not edit.
#
# spawnLocalHost wrote the approval-gate overlay and passed it as
# '--config <path>'. That path is on the daemon's machine only, so this script
# copies the overlay to the far side, checks it arrived intact, rewrites the
# flag, and execs. ompd never authors the overlay and never passes --config
# itself; this only makes the file the daemon wrote reachable.
#
# Exit 78 means the gate could not be guaranteed. An 'omp acp' started without
# the overlay falls back to the operator's global config, and a global
# 'approvalMode: yolo' skips OMP's ACP permission hook entirely: the daemon
# would then see no permission requests and conclude nothing needed approval.
set -eu

fail() {
  echo "ompd wrapper (${label}): $1" >&2
  exit 78
}

# Rewrite --config to the far-side path, leaving every other argument alone.
config=''
n=$#
consumed=0
while [ "$consumed" -lt "$n" ]; do
  arg=$1
  shift
  consumed=$((consumed + 1))
  case $arg in
    --config)
      [ "$consumed" -lt "$n" ] || fail 'saw --config with no value'
      config=$1
      shift
      consumed=$((consumed + 1))
      set -- "$@" --config '${remote}'
      ;;
    --config=*)
      config=\${arg#--config=}
      set -- "$@" '--config=${remote}'
      ;;
    *)
      set -- "$@" "$arg"
      ;;
  esac
done

[ -n "$config" ] || fail 'refusing to start an ACP host with no --config overlay'
[ -r "$config" ] || fail "cannot read the overlay at $config"

${shell} tee '${remote}' < "$config" > /dev/null || fail 'could not place the overlay'
${shell} chmod 600 '${remote}' < /dev/null > /dev/null || fail 'could not lock down the overlay'
${shell} cat '${remote}' < /dev/null | cmp -s - "$config" || fail 'overlay did not arrive intact'

exec ${attach} "$@"
`;
}

/**
 * Write the wrapper into a fresh private directory and return its location.
 *
 * Synchronous, `mkdtempSync`, and `wx` for the same reasons `writeGateConfig`
 * is: an unpredictable 0700 directory created in one step cannot be
 * pre-created world-writable by another local user, and refusing to overwrite
 * means we never follow a planted symlink. Replacing this script would replace
 * the gate.
 */
export function writeGateWrapper(spec: GateWrapperSpec): GateWrapper {
  const script = renderGateWrapper(spec);
  const dir = mkdtempSync(join(tmpdir(), "ompd-host-"));
  const path = join(dir, "omp-wrapper.sh");
  writeFileSync(path, script, { mode: 0o700, flag: "wx" });
  if (readFileSync(path, "utf8") !== script) {
    throw new ProvisionError(`host wrapper at ${path} did not persist intact`, spec.kind);
  }
  return { path, dir };
}
